dist: bionic
sudo: false
notifications:
  email: false
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules
    - $HOME/.gradle
    - .gradle
before_script:
  # sdkman helps to install different gradle versions
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - unset JAVA_HOME
  - export GRADLE_OPTS=-Dorg.gradle.console=verbose
jobs:
  include:
  - stage: Run lint on Node v10
    node_js: 10
    env: Node.js=10
    script:
      - npm run lint

  - stage: Different Node/Java versions + most recent Gradle version
    # We support Node 6+, Java 8+, Gradle 2.14+
    # Tested Java versions are usually: 8 (LTS), 11 (LTS), 13 (latest)
    # (see https://www.oracle.com/technetwork/java/java-se-support-roadmap.html)
    # LTS version are also the most popular ones: https://www.baeldung.com/java-in-2019

    # We use sdkman to install Java.
    # AdoptOpenJDK distribution with HotSpot VM is chosen as the most "classic" option.
    node_js: 6
    env: GRADLE_VERSION=6.0 JDK=8 Node.js=6
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    node_js: 8
    env: GRADLE_VERSION=6.0 JDK=11 Node.js=8
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    node_js: 10
    env: GRADLE_VERSION=6.0 JDK=12 Node.js=10
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    node_js: 12
    env: GRADLE_VERSION=6.0 JDK=13 Node.js=12
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test

  - stage: Older Gradle versions
    # java 9+ and gradle 2 not supported
    env: GRADLE_VERSION=2.14 JDK=8
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    # java 9+ and gradle 3 not supported
    env: GRADLE_VERSION=3.5.1 JDK=8
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    env: GRADLE_VERSION=4.10.3 JDK=8
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    env: GRADLE_VERSION=4.10.3 JDK=11
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    env: GRADLE_VERSION=4.10.3 JDK=13
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    env: GRADLE_VERSION=5.3.1 JDK=8
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    env: GRADLE_VERSION=5.3.1 JDK=11
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test
  -
    # Gradle 5 is not compatible with JDK 13
    # https://github.com/gradle/gradle/issues/8681
    env: GRADLE_VERSION=5.6.4 JDK=12
    script:
      - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*hs-adpt")
      - sdk install gradle $GRADLE_VERSION
      - java -version
      - npm test

  - stage: npm release
    if: branch = master
    node_js: 10
    script: skip
    after_success:
      - npx semantic-release
